Milestone 2 report
pkt-cash/ns-projects pull request #47
Opened 2020-10-02 16:38 UTC by backupbrain

Milestone 2 Report for VPN utility

2020-11-16 09:05 UTC, cjdelisle approved these changes
This milestone has a few parts missing so it could be reasonably argued that it has not been successful, in the original specification was: Server site login, Client site login, App push notifications, App login with pin, which have been deferred.
However registration of a VPN service and cjdns network access (from M3) have been fast-tracked and ended up in M2.
While I acknowledge my own involvement in the project constitutes a conflict, I personally think this is acceptable because the project has shown real material progress and the applicant seems to be committed to completing the project and exploiting the result.

2020-11-20 02:41 UTC, benhylau approved these changes

2020-11-21 00:15 UTC, neilalexander requested changes
I'm impressed to see that quite a bit of functionality has been brought forward from later milestones which has led to some significant progress being made. The fact that the core functionality of the app works is excellent news.

However, I am aware that there are quite a few action points from the original proposal that have been deferred. The milestone report is the perfect place to outline where changes to the original plan have to be made and I would request that the report be updated to outline how these items will be addressed and the orders/estimated timescales anticipated. We will then have the relevant history and context to evaluate deliverables when it comes to reviewing the next milestone report.

2020-11-21 14:04 UTC, backupbrain commented
@neilalexander I like this feedback.  

It's true we deferred some features as we focused on connectivity first instead of the original plan to focus frameworks first.

The other major deviation is that many features outlined in the original plan, including email/sms communication and certain account management features became obsolete once we used cjdns as the authorization mechanism.  This change benefitted us by allowing us to let users connect to a VPN anonymously, without having to provide a name, email, or phone.

2020-11-21 14:04 UTC, merged

2020-11-21 14:49 UTC, cjdelisle commented
@backupbrain please propose an update to the PR to address @neilalexander 's concerns. I don't want to sign it without his concerns addressed.